variables:
  GIT_CLEAN_FLAGS: none # disable git clean ** this is important **

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - python3 --version
    - pip3 install -r requirements.txt
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - echo "deployed successfully :)"
